<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Update="Data\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../LibraryZh.Logic/LibraryZh.Logic.csproj" />
    <ProjectReference Include="../LibraryZh.Repository/LibraryZh.Repository.csproj" />
    <ProjectReference Include="../LibraryZh.Models/LibraryZh.Models.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
