<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../LibraryZh.Models/LibraryZh.Models.csproj" />
    <ProjectReference Include="../LibraryZh.Repository/LibraryZh.Repository.csproj" />
  </ItemGroup>

</Project>
